name: Build RustDesk Windows EXE

on:
  workflow_dispatch:

jobs:
  build-windows:
    uses: ./.github/workflows/flutter-build.yml
    with:
      build-platforms: windows
      upload-artifact: true
      version: 1.3.0
