name: Build RustDesk Windows EXE

on:
  workflow_dispatch:

jobs:
  build-windows:
    uses: ./.github/workflows/flutter-build.yml
    with:
      build-platforms: windows
      upload-artifact: true
      # 可选：这里可以手动指定版本号，例如 "1.3.0"
      # version: 1.3.0
